### ISSUE TITLE
Documentation on creating custom DiM cards?

### ISSUE THREAD

**Issue by skompc** [Ruimusume/DiM_BACKUP#2]
Hi I'm wondering if there is any documentation or guides on how the DiM card is structured? Specifically sprites and evolution data? I'm looking to create my own custom DiM card bins and flash them to a regular DiM card.

**Comment by Ruimusume** [comment]
> Hi I'm wondering if there is any documentation or guides on how the DiM card is structured? Specifically sprites and evolution data? I'm looking to create my own custom DiM card bins and flash them to a regular DiM card.

Maybe Vasquez Electronics@YouTube can help you
