### ISSUE TITLE
請問有提供數碼手環的DIM檔嗎??

### ISSUE THREAD

**Issue by TaChris** [Ruimusume/DiM_BACKUP#6]
如題 謝謝你

**Comment by TaChris** [comment]
![image](https://user-images.githubusercontent.com/94432579/153743644-b87311ac-0472-4b6d-a785-cb811402f9df.png)
請問這種的可以用嗎??

**Comment by Ruimusume** [comment]
> 

槽口太深了接触不了读取不了dim卡，得找示意图上那种短的，不然你得拆了dim卡的塑料壳才能放进你所示的这种配件的卡槽里

**Comment by TaChris** [comment]
了解了 謝謝你
