### ISSUE TITLE
DiM图形素材导出（DiM CARD bin Sprite Dump）這個網頁好像不是正確的

### ISSUE THREAD

**Issue by TaChris** [Ruimusume/DiM_BACKUP#7]
DiM图形素材导出（DiM CARD bin Sprite Dump）
https://github.com/Ruimusume/DiM_CARD/wiki/DiM-bin%E5%9B%BE%E5%BD%A2%E7%B4%A0%E6%9D%90%E5%AF%BC%E5%87%BA

這個網頁好像不是正確的

**Comment by TaChris** [comment]
> DiM圖形素材匯出（DiM CARD bin Sprite Dump） https://github.com/Ruimusume/DiM_CARD/wiki/DiM-bin%E5%9B%BE%E5%BD%A2%E7%B4%A0%E6%9D%90%E5%AF%BC%E5%87%BA
> 
> 這個網頁好像不是正確的

**Comment by Ruimusume** [comment]
> > DiM圖形素材匯出（DiM CARD bin Sprite Dump） https://github.com/Ruimusume/DiM_CARD/wiki/DiM-bin%E5%9B%BE%E5%BD%A2%E7%B4%A0%E6%9D%90%E5%AF%BC%E5%87%BA
> > 這個網頁好像不是正確的

https://github.com/Ruimusume/DiM_BACKUP/wiki/DiM%E5%9B%BE%E5%BD%A2%E7%B4%A0%E6%9D%90%E5%AF%BC%E5%87%BA
